### PR TITLE
Theme fixes - light mode selection color, dark mode container, get html colors from theme manager ...

### LINKED ISSUE #818: Similarly to dark mode, light mode list view selected item should have the same color as selected node.

### PR DESCRIPTION
**Pull request by BinarySoftware**
### Pull Request Description
Small adjustment to make everything feel and look nice, just like selection in dark mode.
(I'm really proud of this colour fyi :) )

Closes #818

Zrzut ekranu 2020-09-30 o 20 36 41

Not only that, but:
- Fixes shadows in dark mode
- Fixes HTML container/documentation view shadows and background color - now gets those colors from manager instead of string literal

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/luna/enso/blob/main/docs/style-guide/rust.md).
- [x] All code has been tested where possible.
- [x] All code has been profiled where possible.

### CODE REVIEW

**Comment by farmaazon** [comment]
Please do all things in checklist if necessary and check them in description

**Comment by BinarySoftware** [comment]
Ok checked 👍

**Review by farmaazon — APPROVED** [review]

**Comment by wdanilo** [comment]
I need to play with different colors before merging this. Lets leave it for the next week.

**Review by wdanilo — APPROVED** [review]

**Comment by BinarySoftware** [comment]
Zrzut ekranu 2020-10-14 o 12 23 42

Approved and fixed

**Pull request merged**
