### PR TITLE
File Open Dialog

### PR DESCRIPTION
**Pull request by farmaazon**
### Pull Request Description
This PR contains the ctrl/cmd + o dialog where user can pick a project to open, and in future the file browser will be displayed.

This PR contains the API for not-yet-implemented file browser component, and the API is already integrated with controllers, and the integration was tested on the old file browser, which, alas, has been reverted.

image

### Checklist
Please include the following checklist in your PR:

- [x] The `CHANGELOG.md` was updated with the changes introduced in this PR.
- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [x] All code has automatic tests where possible.
- [x] All code has been profiled where possible.
- [x] All code has been manually tested in the IDE.
- [x] All code has been manually tested in the "debug/interface" scene.
- [x] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

### CODE REVIEW

**Review by wdanilo — APPROVED** [review]

**Comment by s9ferech** [comment]
When I use the scroll wheel on the file manager then it also scrolls the graph in the background.

**Review by s9ferech — COMMENTED** [review]
If I open the dialogue immediately after starting the IDE then the "Press tab key to search for components" label is in front of it:
press tab

**Comment by s9ferech** [comment]
When a folder cannot be opened, the browser displays a message that was likely not written for users:
error message

**Comment by s9ferech** [comment]
I would suggest to put folders at the top, by default, since that is how I know it from most systems.

I would also propose to use [natural sort order](https://en.wikipedia.org/wiki/Natural_sort_order) among files and folders in the future.

**Comment by s9ferech** [comment]
I would expect that the dialogue closes when I click on the background.

**Comment by s9ferech** [comment]
Since the browser allows to paste files, I think it we should soon add the feature to delete files. I assume this will not be difficult to implement.

**Comment by s9ferech** [comment]
We should probably also soon add an icon for the `Standard.Base` library. At least, it should use the "Project" icon rather than the root icon, in my opinion.

**Comment by s9ferech** [comment]
Dropping files onto the file browser inserts them into the graph behind the browser, which is unexpected for me.

**Comment by s9ferech** [comment]
This is not a surprise, but the file browser does not adopt to narrow windows. Neither does it make good use of large windows.

**Comment by farmaazon** [comment]
Additionally, after navigating in graph, the file browser events are misplaced. I'll tried to apply a workaround, but it does not work.

**Comment by s9ferech** [comment]
The ordering of content roots changes between restarts. A consistent ordering would make it more predictable for the user. This might also affect the ordering of files and folders on some systems, but they were always sorted alphabetically for me.

**Pull request merged**
