### PR TITLE
Fixes documentation text - font and size

### LINKED ISSUE #932: Documentation text size is too big
The documentation text should NOT be bigger than searcher font - it looks bad. The title in docs may be of the same size as body, but bolded or with spacing, but not bigger than text in searcher.

### PR DESCRIPTION
**Pull request by BinarySoftware**
### Pull Request Description
closes #932

Fixes font to be unified with IDE and its size.

Zrzut ekranu 2020-12-8 o 20 27 26

Zrzut ekranu 2020-12-8 o 20 28 38

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guide.
- [x] All code has automatic tests where possible.
- [x] All code has been profiled where possible.
- [x] All code has been manually tested in the IDE.
- [x] All code has been manually tested in the "debug/interface" scene.
- [x] All code has been manually tested by the PR owner against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).
- [ ] All code has been manually tested by at least one reviewer against our [test scenarios](https://docs.google.com/spreadsheets/d/1RatJDM_f9_3bvYhl3Bpq2d8SyKgtVdrV1RkGxPU17c8/edit?ts=5faa7049#gid=0).

### CODE REVIEW

**Comment by wdanilo** [comment]
Hi, amazing, it looks much better now. Few things:

1. Can you show more screenshots of more docs elements here?
2. Can we make the fonts of "Example" smaller as well? Let's TRY (not sure yet if thats correct) them of the size of the main synopsis but bold.
3. Why "Example" is indented? I believe it should not, should it? 
4. The background of example looks bad. Let's try 2 versions here - darker than the normal background, and transparent with 1px or 2px dark (not black) rounded border.

**Review by wdanilo — CHANGES_REQUESTED** [review]
I added comment yestrday but not by using the right option here, so Im just adding note here

**Comment by BinarySoftware** [comment]
1,2,3 addressed in DM, 4, after some DM conversatiions: ( i prefer background instead of border )

Zrzut ekranu 2020-12-16 o 14 28 03

Zrzut_ekranu_2020-12-9_o_21 39 54

**Review by wdanilo — CHANGES_REQUESTED** [review]
1. The fonts are not of the same size, this looks bad:
    image
2. There are no dark-theme screenshots.
3. The second picture looks better IMO. Can we also make a third attempt in which the backgroubnd of the example is darker, but the code has just an outline?

**Comment by BinarySoftware** [comment]
Zrzut ekranu 2020-12-22 o 09 51 21
Zrzut ekranu 2020-12-22 o 09 58 05

**Review by wdanilo — APPROVED** [review]

**Pull request merged**
